name: delivery 
on:
  push:
    branches:
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with GH-Pages
        run: |
          git config user.name "gnidolin" && git config user.email "gnidolin@mail.ru"
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: ./build
