name: Deploy to github pages
on:
 push:
  branches: [ main ]
jobs:
 gh-pages-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Setup Node.js for use with actions
     uses: actions/setup-node@v2
     with:
      version: 18
   - name: Checkout branch
     uses: actions/checkout@v2
   - name: Clean install dependencies
     run: npm ci
   - name: Deploy with gh-pages
     run: |
<<<<<<< HEAD
       git config user.name "gnidolin" && git config user.email "gnidolin@mail.ru"
       npm run deploy
     env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

=======
       git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
       npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 1886a72 (asdas)
