name: Deploy to github pages
on:
  push:
    branches: [ main ]
jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version: 18
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: npm ci
      - name: Run deploy script
        run: |
          git config user.name "gnidolin" && git config user.email "gnidolin@mail.ru"
          npm run gh-pages-deploy
