name: deploy
on: 
  push:
    branches: [main]
jobs:
  # comment
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Setup Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - name: Deploy with GH-Pages
        run: |
          git config user.name "gnidolin" && git config user.email "gnidolin@mail.ru"
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}